--img 640
--batch 32
--epochs 500
--data C:\Users\User\PycharmProjects\Detection\Pothole\data.yaml
--cfg C:\Users\User\PycharmProjects\Detection\yolov5\models\yolov5s.yaml
--weights ''
--name pothole result